services:
  backend:
    env_file:
      - ./src/dev.env
    build:
      context: .
      args:
        app_env: ${APP_ENV}
    volumes:
      - .:/go/src/github.com/odetolakehinde/slack-stickers-be
    ports:
      - "6001:6001"
    depends_on:
      - redis

  redis:
    build: ./redis
    ports:
      - "6321:6321"
