name: golangci-lint-api
on: [pull_request]

jobs:
  golangci-for:
    name: api-golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.61.0

          # Optional: working directory, useful for monorepo
          working-directory: ./

          # Optional: golangci-lint command line arguments.
          args: --config=../.golangci.yml

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
